# docker-compose.yml
version: "3"
services:
  app:
    restart: on-failure
    build: . 
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules